# Generated by Django 5.0.4 on 2024-06-06 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='L1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=60)),
                ('Postnom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60)),
                ('Promotion', models.CharField(max_length=60)),
                ('Séléctionner_Votre_travail', models.FileField(upload_to='PDF')),
            ],
        ),
        migrations.CreateModel(
            name='L1lmdjour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=60)),
                ('Postnom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60)),
                ('Promotion', models.CharField(max_length=60)),
                ('Séléctionner_Votre_travail', models.FileField(upload_to='PDF')),
            ],
        ),
        migrations.CreateModel(
            name='L1lmdsoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=60)),
                ('Postnom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60)),
                ('Promotion', models.CharField(max_length=60)),
                ('Séléctionner_Votre_travail', models.FileField(upload_to='PDF')),
            ],
        ),
        migrations.CreateModel(
            name='L3lmdjour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=60)),
                ('Postnom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60)),
                ('Promotion', models.CharField(max_length=60)),
                ('Séléctionner_Votre_travail', models.FileField(upload_to='PDF')),
            ],
        ),
        migrations.CreateModel(
            name='L3lmdsoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=60)),
                ('Postnom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60)),
                ('Promotion', models.CharField(max_length=60)),
                ('Séléctionner_Votre_travail', models.FileField(upload_to='PDF')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Séléctionner_Votre_travail', models.FileField(upload_to='PDF')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=256, null=True)),
                ('cursus', models.CharField(blank=True, choices=[('Gestion Informatique', 'Gestion Informatique'), ('Réseau', 'Réseau')], max_length=256, null=True)),
                ('promotions', models.CharField(blank=True, choices=[('L1 LMD', 'L1 LMD'), ('L2 LMD', 'L2 LMD'), ('L3 LMD', 'L3 LMD')], max_length=256, null=True)),
                ('vacations', models.CharField(blank=True, choices=[('Jour', 'Jour'), ('Soir', 'Soir')], max_length=256, null=True)),
                ('adresse', models.CharField(blank=True, max_length=256, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=256, null=True)),
                ('telephone', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
