# Generated by Django 5.0.4 on 2024-04-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='L1lmdjour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=60)),
                ('Postnom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60)),
                ('Promotion', models.CharField(max_length=60)),
                ('Séléctionner_Votre_travail', models.FileField(upload_to='PDF')),
            ],
        ),
    ]
